import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { MantineProvider } from "@mantine/core";
import Example from "@/components/Test";
import { Category } from "@/sanity.types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface TestLayoutProps {
  children: React.ReactNode;
  categories: Category[];
}

export default function TestLayout({ children, categories }: TestLayoutProps) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <MantineProvider>
            <main>
              <Example />
              {children}
            </main>
          </MantineProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
